---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      recipe[test::default]
    attributes:
